# docker-compose.yml
# -----------------------
# Docker Compose configuration file for the backend server and MongoDB database. 
# Defines services, environment variables, ports, and volumes for both components. 
# This file allows for easy setup and management of the development environment using Docker.

version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: timesync-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: timesync-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb+srv://jofahariya:Farris12com@clusterswissaxa.7m6ct7j.mongodb.net/fartechdb?appName=ClusterSwissAXA
    depends_on:
      - mongodb
    volumes:
      - ./src:/app/src
      - /app/node_modules

volumes:
  mongodb_data: